### PR TITLE
0.2.1: simple advisor

### PR DESCRIPTION
**Pull request by awitherow**
Figure out how to best buy and sell.

- [x] remove duplication in advisor
- [ ] test`shouldSell` function

### CODE REVIEW

**Comment by jhanstra** [comment]
@awitherow getting an error when running 0.2.1:
```
▲ npm run go

> coinbot@0.2.1 go /Users/jhanstra/JH/learn/coin/coinbot
> node index.js

running BTC at June 3rd 2017, 11:39:38 am
(node:70922) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'details' of undefined
(node:70922) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Are you getting this?

**Comment by awitherow** [comment]
Currently not. Unfortunately my 'test suite' is live data from my trading! so we are getting really different stuff 😂 

BUT the area where you are experiencing errors is within the getLastOrder part.

**Comment by awitherow** [comment]
@jhanstra try looking at what it does now, I added a simplification.

use the `npm run dev` script for live reloading while coding 😉

**Comment by jhanstra** [comment]
@awitherow it works! I'll take a closer look.

**Comment by jhanstra** [comment]
@awitherow this looks great. I would say go for the merge. This is a good base for me to work from too for adding auto trade. What do you think about setting an `AUTO_TRADE` env flag and adding trade functionality alongside the advising functionality? Then within the advisor we do `if (AUTO_TRADE) { makeTrade() } else { adviseTrade() }`

**Comment by awitherow** [comment]
@jhanstra excellent. can you make an issue for that? I will make a few issues for features/ideas I have as well 👍 merging!

**Pull request merged**
